// Synthetic release-review notes with several independent subjects. No secrets
// or observations from an operator's actual workspace are included.
export const reviewNotes = [
	'Deployment: The regional rollout remained paused while the reviewer compared the staging checklist with the signed release manifest. The canary group had completed its observation window, but the evidence for the remaining regions was still distributed across earlier inspection steps.',
	'Routing: The network review separated the ingress configuration from the destination assigned to each shipment. A healthy connection did not prove that the destination itself was correct. The reviewer requested original receipts rather than inferring addresses from successful connectivity checks.',
	'Packaging: The packaging team reviewed labels, container seals and batch counts. Two labels had been photographed before the final handoff. Later photographs described the current containers; the earlier images remained relevant only to questions about the original handoff.',
	'Migration: The database migration was assessed independently of the deployment schedule. The dry run established that the schema change could complete on a copy. It did not establish that a production migration had happened, nor that a later rollback would restore all external effects.',
	'Documentation: The release notes linked each reported behavior to its corresponding test or source inspection. Several pages still described earlier command names. The reviewer treated these as documentation corrections and avoided assuming that all archived examples reflected the installed build.',
	'Authentication: The credential review distinguished discovery, refresh and request authorization. Finding a configured account was insufficient to prove that the next request would succeed. Error receipts were retained with their actual provider status rather than being rewritten as generic connection failures.',
	'Permissions: The approval review checked which actions had been authorized before execution. Read access to an archive did not grant permission to repeat the operation that originally produced it. The report recorded interrupted actions separately from actions with confirmed completion receipts.',
	'Storage: The archive review compared immutable records with mutable workspace files. Removing a workspace note did not remove a retained observation. Conversely, finding an old observation did not prove that its content still described the current file, configuration or deployment state.',
	'Capacity: The scheduler review counted admitted work separately from waiting tasks. Idle checks did not invoke a model. A failed invocation could still have consumed resources, so the accounting included failed and interrupted attempts rather than measuring only completed responses.',
	'Testing: The reviewer separated deterministic controls from real provider trials. Scripted responses established what information reached a request, while live responses established what that particular model did with the information. Neither small test set justified a general performance ranking.',
	'Accessibility: The interface review checked narrow terminal widths, keyboard navigation and labels that persisted while a task was waiting. It also considered whether status colors conveyed information that was unavailable in text. Decorative changes were evaluated separately from task correctness.',
	'Recovery: The recovery review preserved the exact admitted claim when an executor stopped before settlement. Process exit did not automatically establish that all effects were complete. A new executor needed inspected recovery state before it could safely continue the same authorized work.',
	'Observability: The operator wanted enough evidence to understand decisions without exposing private authentication material. Request summaries therefore recorded model selection, result availability and usage, while deliberately keeping credential payloads out of the published experiment artifacts.',
	'Distribution: The package review followed the dependency graph from the runtime to the optional adapters and then to the command-line application. A successful local build was not treated as proof of publication. Consumer installation and registry checks belonged to a separate release decision.',
	'Coordination: The reviewer distinguished a new workflow from a later phase inside an existing workflow. Reusing a label did not establish that two independently admitted tasks belonged to the same plan. Each completed observation retained its original task and invocation address.',
	'Verification: The final report was expected to distinguish direct observations, accepted operator corrections and derived summaries. Conflicting observations were to remain separately addressable. The reviewer would decide what followed from them after receiving the outstanding original reference.',
].join('\n\n')
