import assert from 'node:assert/strict'
import { mkdtemp, mkdir, writeFile, readFile } from 'node:fs/promises'
import { createRequire } from 'node:module'
import { tmpdir } from 'node:os'
import { join, resolve } from 'node:path'
const repo = resolve(process.argv[2] ?? '.')
const require = createRequire(join(repo, 'packages/desktop/package.json'))
const { _electron, expect } = require('@playwright/test')
const root = await mkdtemp(join(tmpdir(), 'namzu-native-smoke-'))
const project = join(root, 'project'); const home = join(root, 'namzu'); const uiHome = join(root, 'desktop')
await mkdir(join(project, '.git'), { recursive: true }); await mkdir(home); await mkdir(uiHome)
await writeFile(join(project, 'namzu.config.json'), JSON.stringify({ sandbox: { enabled: false } }))
await writeFile(join(home, 'preferences.json'), JSON.stringify({ version: 3, providers: [{ id: 'anthropic', model: 'claude-sonnet-4-5' }], subagents: { active: [] } }))
const receipts = join(root, 'requests.jsonl')
const launchOptions = { executablePath: require('electron'), args: [join(repo, 'packages/desktop'), `--user-data-dir=${uiHome}`], env: { ...process.env, NAMZU_HOME: home, ANTHROPIC_API_KEY: 'synthetic-not-a-secret', NAMZU_DESKTOP_CLI: join(repo, 'research/runtime-desktop-20260930/fixtures/scripted-cli.mjs'), NAMZU_TEST_RECEIPTS: receipts } }
let desktop = await _electron.launch(launchOptions)
try {
	await desktop.evaluate(({ app, dialog }, args) => {
		app.setPath('userData', args.uiHome)
		dialog.showOpenDialog = async () => ({ canceled: false, filePaths: [args.project] })
		dialog.showMessageBox = async () => ({ response: 1, checkboxChecked: false })
	}, { uiHome, project })
	const page = await desktop.firstWindow()
	const faults = []; page.on('pageerror', (error) => faults.push(error.message))
	await expect(page.getByRole('heading', { name: 'What are we building?' })).toBeVisible()
	await page.getByRole('button', { name: 'Open a project', exact: true }).last().click()
	await page.getByRole('button', { name: 'Review folder access' }).click()
	await expect(page.getByRole('heading', { name: 'Ready when you are.' })).toBeVisible()
	await page.locator('.welcome').getByRole('button', { name: 'New conversation', exact: true }).click()
	await page.getByRole('textbox', { name: 'Model', exact: true }).fill('claude-opus-4-7')
	await page.getByRole('textbox', { name: 'Message Namzu' }).fill('Run the foreground fixture.')
	await page.getByRole('button', { name: 'Send message' }).click()
	await expect(page.getByRole('region', { name: 'Tool approval' })).toBeVisible()
	await page.getByRole('textbox', { name: 'Message Namzu' }).fill('Start the background fixture next.')
	await page.getByRole('button', { name: 'Queue message' }).click()
	await expect(page.locator('.queue')).toContainText('1 queued')
	await page.reload()
	await page.locator('.conversations').getByRole('button', { name: 'Run the foreground fixture.' }).click()
	await expect(page.locator('.queue')).toContainText('1 queued')
	await expect(page.getByRole('textbox', { name: 'Model', exact: true })).toHaveValue('claude-opus-4-7')
	await expect(page.getByRole('region', { name: 'Tool approval' })).toBeVisible()
	await page.getByRole('button', { name: 'Allow once' }).click()
	await expect(page.getByRole('region', { name: 'Tool approval' })).toContainText('run_in_background')
	await page.getByRole('button', { name: 'Allow once' }).click()
	await expect(page.locator('.message-text').filter({ hasText: 'The background process is running.' })).toBeVisible()
	await page.getByRole('button', { name: /Background work/ }).click()
	await expect(page.locator('.job')).toContainText('running')
	await page.getByRole('button', { name: 'View output' }).click()
	await expect(page.locator('.job-output')).toContainText('BACKGROUND_PIPE_OK')
	await page.getByRole('button', { name: 'Stop', exact: true }).click()
	await expect(page.locator('.job')).not.toContainText('running')
	await page.getByRole('button', { name: 'Close background work' }).click()
	await page.emulateMedia({ reducedMotion: 'reduce' })
	const composer = page.getByRole('textbox', { name: 'Message Namzu' })
	await composer.fill('Unsent composed text')
	await composer.evaluate((node) => node.dispatchEvent(new KeyboardEvent('keydown', { key: 'Enter', isComposing: true, bubbles: true })))
	await expect(composer).toHaveValue('Unsent composed text')
	await composer.press('Shift+Enter')
	await expect(composer).toHaveValue('Unsent composed text\n')
	await page.screenshot({ path: join(repo, 'research/runtime-desktop-20260930/artifacts/native-wide.png') })
	await desktop.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows()[0].setSize(600, 540))
	await page.screenshot({ path: join(repo, 'research/runtime-desktop-20260930/artifacts/native-narrow.png') })
	assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > window.innerWidth), false)
	assert.equal(await page.evaluate(() => typeof window.require), 'undefined')
	assert.equal(await page.evaluate(() => typeof window.process), 'undefined')
	assert.deepEqual(faults, [])
	const requests = (await readFile(receipts, 'utf8')).trim().split('\n').map(JSON.parse)
	assert.equal(requests.filter((request) => request.purpose === 'agent').length, 4)
	assert.ok(requests.some((request) => request.purpose === 'evidence-query'))
	assert.ok(requests.filter((request) => request.purpose === 'agent').every((request) => request.model === 'claude-opus-4-7'))
	await desktop.close()
	desktop = await _electron.launch(launchOptions)
	assert.equal(await desktop.evaluate(({ app }) => app.getPath('userData')), uiHome)
	const restored = await desktop.firstWindow()
	await restored.locator('.conversations').getByRole('button', { name: 'Run the foreground fixture.' }).click()
	await expect(restored.locator('.message-text').filter({ hasText: 'Native runtime answered. DESKTOP_PIPE_OK' })).toBeVisible()
	await expect(restored.locator('.message-text').filter({ hasText: 'The background process is running.' })).toBeVisible()
	await expect(restored.getByRole('button', { name: 'Send message' })).toBeVisible()
	console.log(JSON.stringify({ native: true, realCli: true, realKernel: true, modelIo: 'scripted', actualShell: ['foreground', 'background', 'stop'], queuedNextTurn: true, reloadRetainsReviewAndQueue: true, selectedModelReachedKernel: true, historySurvivesAppRestart: true, imeDoesNotSubmit: true, shiftEnterNewline: true, permissions: 'two separate approvals', rendererNode: false, overflow: false, requests, root }))
} finally { await desktop.close() }
