import assert from 'node:assert/strict'
import { mkdtemp, mkdir, writeFile, readFile } from 'node:fs/promises'
import { createRequire } from 'node:module'
import { tmpdir } from 'node:os'
import { join, resolve } from 'node:path'
const repo = resolve(process.argv[2] ?? '.')
const require = createRequire(join(repo, 'packages/desktop/package.json'))
const { _electron, expect } = require('@playwright/test')
const root = await mkdtemp(join(tmpdir(), 'namzu-native-smoke-'))
const project = join(root, 'project'); const home = join(root, 'namzu'); const uiHome = join(root, 'desktop')
await mkdir(join(project, '.git'), { recursive: true }); await mkdir(home); await mkdir(uiHome)
await writeFile(join(project, 'namzu.config.json'), JSON.stringify({ sandbox: { enabled: false } }))
await writeFile(join(home, 'preferences.json'), JSON.stringify({ version: 3, providers: [{ id: 'anthropic', model: 'claude-sonnet-4-5' }], subagents: { active: [] } }))
const receipts = join(root, 'requests.jsonl')
const launchOptions = { executablePath: require('electron'), args: [join(repo, 'packages/desktop'), `--user-data-dir=${uiHome}`], env: { ...process.env, NAMZU_HOME: home, ANTHROPIC_API_KEY: 'synthetic-not-a-secret', NAMZU_DESKTOP_CLI: join(repo, 'research/runtime-desktop-20260930/fixtures/scripted-cli.mjs'), NAMZU_TEST_RECEIPTS: receipts } }
async function settleMotion(page) {
	await page.evaluate(async () => {
		await Promise.all(document.getAnimations()
			.filter((animation) => animation.effect?.getTiming().iterations !== Infinity)
			.map((animation) => animation.finished.catch(() => undefined)))
	})
}
// Observe the state mutation in the same browser task, so a loaded host cannot
// finish the motion before we inspect it. Advance animation time explicitly.
async function probePanelMotion(page) {
	return page.evaluate(async () => {
		const panel = document.querySelector('.jobs-panel')
		getComputedStyle(panel).transform
		return await new Promise((resolve) => {
			const observer = new MutationObserver(() => {
				if (panel.dataset.open !== 'true') return
				observer.disconnect()
				const animations = panel.getAnimations()
				const frames = animations.map((animation) => {
					animation.pause()
					const duration = Number(animation.effect.getTiming().duration)
					animation.currentTime = duration / 2
					return { property: animation.transitionProperty, duration, easing: animation.effect.getTiming().easing }
				})
				const midTransform = getComputedStyle(panel).transform
				for (const animation of animations) animation.finish()
				resolve({ frames, midTransform, endTransform: getComputedStyle(panel).transform })
			})
			observer.observe(panel, { attributes: true, attributeFilter: ['data-open'] })
			document.querySelector('.jobs-button').click()
		})
	})
}
let desktop = await _electron.launch(launchOptions)
try {
	await desktop.evaluate(({ app, dialog }, args) => {
		app.setPath('userData', args.uiHome)
		dialog.showOpenDialog = async () => ({ canceled: false, filePaths: [args.project] })
		dialog.showMessageBox = async () => ({ response: 1, checkboxChecked: false })
	}, { uiHome, project })
	const page = await desktop.firstWindow()
	const faults = []; page.on('pageerror', (error) => faults.push(error.message))
	await expect(page.getByRole('heading', { name: 'What would you like to work on?' })).toBeVisible()
	await expect(page.getByRole('img', { name: 'Namzu' })).toHaveCount(2)
	assert.equal(await page.locator('.brand .namzu-wordmark').textContent(), '█▄ █ ▄▀█ █▀▄▀█ ▀█ █ █\n█ ▀█ █▀█ █ ▀ █ █▄ █▄█')
	assert.equal(await page.locator('.brand .namzu-wordmark').evaluate((node) => getComputedStyle(node).color), 'rgb(95, 255, 95)')
	await settleMotion(page)
	await settleMotion(page)
	await page.screenshot({ path: join(repo, 'research/runtime-desktop-20260930/artifacts/native-welcome.png') })
	await page.getByRole('button', { name: 'Open a project', exact: true }).last().click()
	await page.getByRole('button', { name: 'Review folder access' }).click()
	await expect(page.getByRole('heading', { name: 'Start something new' })).toBeVisible()
	await page.locator('.welcome').getByRole('button', { name: 'New conversation', exact: true }).click()
	await page.getByRole('button', { name: 'Select model', exact: true }).click()
	await page.getByRole('textbox', { name: 'Model', exact: true }).fill('claude-opus-4-7')
	await page.getByRole('button', { name: 'Use model', exact: true }).click()
	await expect(page.getByRole('button', { name: 'Select model', exact: true })).toBeFocused()
	await page.getByRole('textbox', { name: 'Message Namzu' }).fill('Run the foreground fixture.')
	await page.getByRole('button', { name: 'Send message' }).click()
	await expect(page.getByRole('region', { name: 'Tool approval' })).toBeVisible()
	await page.getByRole('textbox', { name: 'Message Namzu' }).fill('Start the background fixture next.')
	await page.getByRole('button', { name: 'Queue message' }).click()
	await expect(page.locator('.queue')).toContainText('1 queued')
	await page.reload()
	await page.locator('.conversations').getByRole('button', { name: 'Run the foreground fixture.' }).click()
	await expect(page.locator('.queue')).toContainText('1 queued')
	await expect(page.getByRole('button', { name: 'Select model', exact: true })).toContainText('claude-opus-4-7')
	await expect(page.getByRole('region', { name: 'Tool approval' })).toBeVisible()
	await settleMotion(page)
	await page.screenshot({ path: join(repo, 'research/runtime-desktop-20260930/artifacts/native-approval.png') })
	await page.getByRole('button', { name: 'Allow once' }).click()
	await expect(page.getByRole('region', { name: 'Tool approval' })).toContainText('run_in_background')
	await page.getByRole('button', { name: 'Allow once' }).click()
	await expect(page.locator('.message-text').filter({ hasText: 'The background process is running.' })).toBeVisible()
	const panelMotion = await probePanelMotion(page)
	assert.ok(panelMotion.frames.some((frame) => frame.property === 'transform' && frame.duration === 220))
	assert.notEqual(panelMotion.midTransform, panelMotion.endTransform)
	await settleMotion(page)
	await expect(page.locator('.job')).toContainText('running')
	await page.getByRole('button', { name: 'View output' }).click()
	await expect(page.locator('.job-output')).toContainText('BACKGROUND_PIPE_OK')
	await settleMotion(page)
	await page.screenshot({ path: join(repo, 'research/runtime-desktop-20260930/artifacts/native-jobs.png') })
	await page.getByRole('button', { name: 'Stop', exact: true }).click()
	await expect(page.locator('.job')).not.toContainText('running')
	await page.getByRole('button', { name: 'Close background work' }).click()
	await page.getByRole('searchbox', { name: 'Search conversations' }).fill('no matching title')
	await expect(page.getByText('No conversations found.')).toBeVisible()
	await page.getByRole('searchbox', { name: 'Search conversations' }).fill('')
	await expect(page.locator('.conversations').getByRole('button', { name: 'Run the foreground fixture.' })).toBeVisible()
	await expect(page.locator('html')).toHaveClass('dark')
	await page.emulateMedia({ reducedMotion: 'reduce' })
	const reducedPanelMotion = await probePanelMotion(page)
	assert.equal(reducedPanelMotion.frames.length, 0)
	await expect(page.getByRole('region', { name: 'Tool approval' })).toHaveCount(0)
	await page.getByRole('button', { name: 'Close background work' }).click()
	await expect(page.getByRole('complementary', { name: 'Background work' })).not.toBeVisible()
	const composer = page.getByRole('textbox', { name: 'Message Namzu' })
	await composer.fill('Unsent composed text')
	await composer.evaluate((node) => node.dispatchEvent(new KeyboardEvent('keydown', { key: 'Enter', isComposing: true, bubbles: true })))
	await expect(composer).toHaveValue('Unsent composed text')
	await composer.press('Shift+Enter')
	await expect(composer).toHaveValue('Unsent composed text\n')
	await settleMotion(page)
	await page.screenshot({ path: join(repo, 'research/runtime-desktop-20260930/artifacts/native-wide.png') })
	const geometry = await page.evaluate(() => {
  const read = (selector) => {const node = document.querySelector(selector);const box=node.getBoundingClientRect();const css=getComputedStyle(node);return {width:box.width,height:box.height,fontSize:css.fontSize,lineHeight:css.lineHeight,radius:css.borderRadius,background:css.backgroundColor}}
  return {viewport:{width:innerWidth,height:innerHeight},rootFont:getComputedStyle(document.documentElement).fontSize,sidebar:read('.sidebar'),topbar:read('.topbar'),composer:read('[data-slot=composer-host]'),message:read('.message-text'),model:read('.model-picker-trigger'),canvas:getComputedStyle(document.body).backgroundColor}
 })
 assert.equal(geometry.sidebar.width, 256)
 assert.equal(geometry.topbar.height, 52)
 assert.equal(geometry.rootFont, '16px')
 assert.equal(geometry.message.fontSize, '14px')
 assert.equal(geometry.canvas, 'rgb(11, 15, 12)')
 await writeFile(join(repo, 'research/runtime-desktop-20260930/artifacts/ui-measurements.json'), JSON.stringify(geometry,null,2)+'\n')
 await page.getByRole('button', {name:'Select model', exact:true}).click()
 await settleMotion(page)
	await page.screenshot({path:join(repo,'research/runtime-desktop-20260930/artifacts/native-model-menu.png')})
 await page.getByRole('textbox', {name:'Model', exact:true}).press('Escape')
 await expect(page.getByRole('button', {name:'Select model',exact:true})).toBeFocused()
 await page.getByRole('button', {name:'Appearance: dark. Change appearance',exact:true}).click()
 await expect(page.locator('html')).not.toHaveClass('dark')
 await settleMotion(page)
	await page.screenshot({path:join(repo,'research/runtime-desktop-20260930/artifacts/native-light.png')})
 await page.reload()
 await expect(page.locator('html')).not.toHaveClass('dark')
 await page.locator('.conversations').getByRole('button',{name:'Run the foreground fixture.'}).click()
 await page.getByRole('button',{name:'Appearance: light. Change appearance',exact:true}).click()
 await page.getByRole('button',{name:'Appearance: system. Change appearance',exact:true}).click()
 await expect(page.locator('html')).toHaveClass('dark')
 await desktop.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows()[0].setSize(600, 540))
	await settleMotion(page)
	await page.screenshot({ path: join(repo, 'research/runtime-desktop-20260930/artifacts/native-narrow.png') })
	assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > window.innerWidth), false)
 await expect(page.getByRole('searchbox',{name:'Search conversations'})).not.toBeVisible()
 await page.getByRole('button',{name:'Toggle sidebar',exact:true}).click()
 await expect(page.getByRole('searchbox',{name:'Search conversations'})).toBeVisible()
 await page.keyboard.press('Escape')
 await expect(page.getByRole('searchbox',{name:'Search conversations'})).not.toBeVisible()
 await page.getByRole('button',{name:'Select model',exact:true}).click()
 const popup=await page.locator('[data-slot=popover-popup]').boundingBox()
 assert.ok(popup && popup.x>=0 && popup.y>=0 && popup.x+popup.width<=600 && popup.y+popup.height<=540)
 await page.keyboard.press('Escape')
	assert.equal(await page.evaluate(() => typeof window.require), 'undefined')
	assert.equal(await page.evaluate(() => typeof window.process), 'undefined')
	assert.deepEqual(faults, [])
	const requests = (await readFile(receipts, 'utf8')).trim().split('\n').map(JSON.parse)
	assert.equal(requests.filter((request) => request.purpose === 'agent').length, 4)
	assert.ok(requests.some((request) => request.purpose === 'evidence-query'))
	assert.ok(requests.filter((request) => request.purpose === 'agent').every((request) => request.model === 'claude-opus-4-7'))
	await desktop.close()
	desktop = await _electron.launch(launchOptions)
	assert.equal(await desktop.evaluate(({ app }) => app.getPath('userData')), uiHome)
	const restored = await desktop.firstWindow()
	await restored.locator('.conversations').getByRole('button', { name: 'Run the foreground fixture.' }).click()
	await expect(restored.locator('.message-text').filter({ hasText: 'Native runtime answered. DESKTOP_PIPE_OK' })).toBeVisible()
	await expect(restored.locator('.message-text').filter({ hasText: 'The background process is running.' })).toBeVisible()
	await expect(restored.getByRole('button', { name: 'Send message' })).toBeVisible()
	console.log(JSON.stringify({ native: true, realCli: true, realKernel: true, modelIo: 'scripted', actualShell: ['foreground', 'background', 'stop'], queuedNextTurn: true, reloadRetainsReviewAndQueue: true, selectedModelReachedKernel: true, historySurvivesAppRestart: true, imeDoesNotSubmit: true, shiftEnterNewline: true, modelMenuKeyboard: true, search: true, themePersisted: true, responsiveMenu: true, referenceGeometry: geometry, panelMotion, reducedPanelMotion, cliWordmark: true, permissions: 'two separate approvals', rendererNode: false, overflow: false, requests, root }))
} finally { await desktop.close() }
