export const DEFAULT_BREAKER_FAILURE_THRESHOLD = 5
export const DEFAULT_BREAKER_RESET_TIMEOUT_MS = 30_000
export const DEFAULT_LOCK_TIMEOUT_MS = 60_000
export const DEFAULT_LOCK_ACQUIRE_TIMEOUT_MS = 5_000
export const LOCK_ACQUIRE_POLL_INTERVAL_MS = 100
export const DEFAULT_MAX_LOCKS_PER_AGENT = 10
