import { readFileSync } from 'node:fs'

import { listenerTokenPath } from './paths.js'

/**
 * Read and trim the bearer token clawtool writes for HTTP auth.
 *
 * Token format: 64 hex characters (32 bytes of `crypto/rand`), newline-
 * terminated, mode 0600 — generated by `internal/server/http.go:362-366`.
 * `strings.TrimSpace` is applied server-side at parse time, so leading /
 * trailing whitespace is tolerated. We mirror that here for parity.
 *
 * Throws `ClawtoolAuthError` if the file is missing or empty; callers
 * should surface an actionable message ("daemon not running? run
 * `clawtool daemon start`"). Override `path` for tests.
 */
export class ClawtoolAuthError extends Error {
	constructor(
		message: string,
		readonly cause?: unknown,
	) {
		super(message)
		this.name = 'ClawtoolAuthError'
	}
}

export function readToken(path?: string): string {
	const target = path ?? listenerTokenPath()
	let raw: string
	try {
		raw = readFileSync(target, 'utf8')
	} catch (err) {
		throw new ClawtoolAuthError(
			`clawtool listener token not found at ${target} — is the daemon running?`,
			err,
		)
	}
	const token = raw.trim()
	if (token.length === 0) {
		throw new ClawtoolAuthError(`clawtool listener token at ${target} is empty`)
	}
	return token
}

/**
 * Non-throwing variant. Returns `null` if the token file is missing or
 * empty — which is the expected case when the daemon is running in
 * `--no-auth` mode (single-user loopback). Callers in that path should
 * proceed with no bearer header; clawtool ignores `Authorization` when
 * no-auth is on.
 */
export function tryReadToken(path?: string): string | null {
	const target = path ?? listenerTokenPath()
	try {
		const raw = readFileSync(target, 'utf8')
		const token = raw.trim()
		return token.length > 0 ? token : null
	} catch {
		return null
	}
}
