// Adversarial scroll check: reader scrolls up mid-stream (must stay put), then returns to the end (must follow again).
import { require, startServer } from './serve.mjs'
const { chromium } = require('@playwright/test')
const { server, origin } = await startServer()
const browser = await chromium.launch({ headless: true, args: ['--enable-unsafe-swiftshader'] })
const page = await browser.newPage({ viewport: { width: 1280, height: 900 } })
await page.goto(`${origin}?stress=60`)
await page.waitForFunction(() => document.querySelectorAll('.transcript-turn').length >= 60, null, { timeout: 60000 })
await page.waitForTimeout(500)
await page.evaluate(() => { window.__done = window.namzuPreviewStress.start({ paragraphs: 3, chunkChars: 24, intervalMs: 16 }) })
await page.waitForTimeout(1500)
const gap = () => page.evaluate(() => { const el = document.querySelector('.transcript'); return Math.round(el.scrollHeight - el.clientHeight - el.scrollTop) })
console.log('streaming gap', await gap())
const box = await page.locator('.transcript').boundingBox()
await page.mouse.move(box.x + box.width / 2, box.y + box.height / 2)
await page.mouse.wheel(0, -600)
await page.waitForTimeout(100)
const top0 = await page.evaluate(() => document.querySelector('.transcript').scrollTop)
await page.waitForTimeout(1500)
const top1 = await page.evaluate(() => document.querySelector('.transcript').scrollTop)
console.log('scrolled up: top before/after 1.5s', top0, top1, 'gap', await gap())
await page.mouse.wheel(0, 100000)
await page.waitForTimeout(1200)
console.log('back at end: gap', await gap())
await page.evaluate(() => window.__done)
await page.screenshot({ path: process.env.SHOT ?? '/tmp/adv.png' })
await browser.close(); await server.close()
