import { chromium } from 'playwright'
const out = '/home/arda/workspaces/@cogitave/cogitave/namzu/research/harness-in-picker-20261007'
const b = await chromium.launch({ args: ['--use-gl=angle', '--use-angle=swiftshader'] })
for (const [theme, vw, vh] of [['dark', 1440, 900], ['light', 900, 720]]) {
	const ctx = await b.newContext({ viewport: { width: vw, height: vh } })
	await ctx.addInitScript((t) => { try { localStorage.setItem('namzu.appearance', t) } catch {} }, theme)
	const p = await ctx.newPage()
	p.on('pageerror', (e) => console.log('ERR', e.message))
	const shot = async (name) => { await p.waitForTimeout(500); await p.screenshot({ path: `${out}/${theme}-${name}.png` }); console.log('shot', theme, name) }
	await p.goto('http://127.0.0.1:5173/preview')
	await p.waitForTimeout(2500)
	// started conversation
	await shot('1-started-no-tray')
	console.log('tray count started', await p.locator('[data-slot="composer-context-strip"]').count())
	// new conversation
	await p.getByRole('button', { name: 'New conversation', exact: true }).first().click()
	await p.waitForTimeout(1200)
	console.log('tray count new', await p.locator('[data-slot="composer-context-strip"]').count(), 'harness chip in tray', await p.locator('.composer-context-above [aria-label*="engine" i]').count())
	await shot('2-new-with-tray')
	// effort panel on the new conversation
	await p.locator('.model-picker-trigger').click()
	await p.waitForTimeout(500)
	await shot('3-effort-panel-new')
	const stops = await p.locator('.composer-effort-stop').count()
	console.log('stops', stops, 'default marks', await p.locator('.composer-effort-stop[data-default]').count(), 'reset btn', await p.getByLabel('Use default effort').count())
	console.log('valuetext', await p.locator('input[type=range]').getAttribute('aria-valuetext'))
	// move to the last stop then double-click to reset
	const track = p.locator('.composer-effort-control')
	const box = await track.boundingBox()
	await p.mouse.click(box.x + box.width - 14, box.y + box.height / 2)
	await p.waitForTimeout(500)
	console.log('after click value', await p.locator('.composer-effort-value').textContent(), await p.locator('input[type=range]').getAttribute('aria-valuetext'))
	await shot('4-effort-moved')
	await p.locator('.composer-effort-thumb').dblclick()
	await p.waitForTimeout(500)
	console.log('after dblclick value', await p.locator('.composer-effort-value').textContent(), await p.locator('input[type=range]').getAttribute('aria-valuetext'))
	await shot('5-effort-double-click-reset')
	// engine view from effort (new conversation)
	await p.getByRole('button', { name: /^Engine:/ }).click()
	await p.waitForTimeout(500)
	await shot('6-engine-view-new')
	await p.locator('.engine-panel-back').click()
	await p.waitForTimeout(400)
	// list view with chip
	await p.getByRole('button', { name: /change model/ }).click()
	await p.waitForTimeout(500)
	await shot('7-list-with-chip')
	await p.keyboard.press('Escape')
	await p.waitForTimeout(300)
	// started conversation: engine view locked
	await p.getByRole('button', { name: 'Open Refine navigation' }).first().click().catch(async () => { await p.getByText('Refine navigation').first().click() })
	await p.waitForTimeout(1500)
	console.log('tray count started again', await p.locator('[data-slot="composer-context-strip"]').count())
	await p.locator('.model-picker-trigger').click()
	await p.waitForTimeout(500)
	await shot('8-effort-panel-started')
	await p.getByRole('button', { name: /^Engine:/ }).click()
	await p.waitForTimeout(500)
	await shot('9-engine-view-started-new-tab-note')
	// trigger with another engine
	await p.getByRole('radio', { name: /Codex/ }).click()
	await p.waitForTimeout(2500)
	await shot('10-after-choosing-codex-original-tab-unchanged')
	// the engine was bound to the new conversation the choice opened
	await p.getByText('Sample draft', { exact: true }).nth(1).click()
	await p.waitForTimeout(2500)
	await shot('11-new-codex-conversation-trigger-icon')
	await p.locator('.model-picker-trigger').click()
	await p.waitForTimeout(700)
	await shot('12-codex-effort-panel')
	await p.getByRole('button', { name: /^Engine:/ }).click()
	await p.waitForTimeout(500)
	await shot('13-engine-view-codex-current')
	await ctx.close()
}
await b.close()
