import type { ModelInputModality, ReasoningEffort } from '@namzu/sdk'

/** Zen's independently routed, billed services. */
export type ZenService = 'zen' | 'go'

/** Native wire format documented for this exact model and service. */
export type ZenProtocol = 'chat' | 'responses' | 'messages' | 'google'

/** A supported model in the pinned Zen catalogue. */
export interface ZenModel {
	readonly id: string
	readonly name: string
	readonly protocol: ZenProtocol
	readonly contextWindow?: number
	readonly maxOutputTokens?: number
	readonly inputModalities?: readonly ModelInputModality[]
	/** USD per million uncached input tokens at the documented base tier. */
	readonly inputPrice: number
	/** USD per million output tokens at the documented base tier. */
	readonly outputPrice: number
	readonly supportsToolUse: boolean
	readonly supportsStreaming: boolean
	/** Exact advertised selectable effort levels; empty means no effort selector. */
	readonly effortLevels?: readonly ReasoningEffort[]
}

/*
 * Snapshot: 2026-09-07. Routes and prices come from Zen's own docs:
 * https://github.com/anomalyco/opencode/blob/ecbc6ccac85b3e8087b6445e584318419b9e2b34/packages/web/src/content/docs/zen.mdx
 * https://github.com/anomalyco/opencode/blob/ecbc6ccac85b3e8087b6445e584318419b9e2b34/packages/web/src/content/docs/go.mdx
 * Limits, tool support, modalities and effort options come from the matching
 * provider entries (including their base_model inheritance) in models.dev:
 * https://github.com/anomalyco/models.dev/tree/1a84fdd72ad6c7f507af96aafbcc59a2f818f9fd/providers/opencode
 * https://github.com/anomalyco/models.dev/tree/1a84fdd72ad6c7f507af96aafbcc59a2f818f9fd/providers/opencode-go
 *
 * Prices are estimates, not invoices: context tiers, cache, Go peak/off-peak
 * rates, subscription allowances and promotions can change the effective cost.
 * Go DeepSeek entries use off-peak prices. GPT 5.6 Sol includes the documented
 * 50% promotion through 2026-09-18. PDF input is the SDK's document modality;
 * audio/video are omitted because the SDK does not expose those input kinds.
 *
 * Promotional free models with documented routes and complete metadata are
 * included at their advertised zero price; the service enforces access limits.
 * Deprecated models are omitted. Unknown IDs have no inferred protocol or limits.
 * MiniMax and Qwen demonstrate why routes must be recorded per service/model.
 */
function freezeModels(models: ZenModel[]): readonly ZenModel[] {
	for (const model of models) {
		if (model.inputModalities) Object.freeze(model.inputModalities)
		if (model.effortLevels) Object.freeze(model.effortLevels)
		Object.freeze(model)
	}
	return Object.freeze(models)
}

const ZEN_MODELS = freezeModels([
	{
		id: 'gpt-6-astra',
		name: 'GPT 6 Astra',
		protocol: 'responses',
		contextWindow: 1050000,
		maxOutputTokens: 128000,
		inputModalities: ['text', 'image', 'document'],
		inputPrice: 10.0,
		outputPrice: 50.0,
		supportsToolUse: true,
		supportsStreaming: true,
		effortLevels: ['low', 'medium', 'high', 'xhigh', 'max'],
	},
	{
		id: 'gpt-5.6-sol',
		name: 'GPT 5.6 Sol',
		protocol: 'responses',
		contextWindow: 1050000,
		maxOutputTokens: 128000,
		inputModalities: ['text', 'image', 'document'],
		inputPrice: 2.0,
		outputPrice: 10.0,
		supportsToolUse: true,
		supportsStreaming: true,
		effortLevels: ['none', 'low', 'medium', 'high', 'xhigh', 'max'],
	},
	{
		id: 'gpt-5.6-terra',
		name: 'GPT 5.6 Terra',
		protocol: 'responses',
		contextWindow: 1050000,
		maxOutputTokens: 128000,
		inputModalities: ['text', 'image', 'document'],
		inputPrice: 2.0,
		outputPrice: 12.0,
		supportsToolUse: true,
		supportsStreaming: true,
		effortLevels: ['none', 'low', 'medium', 'high', 'xhigh', 'max'],
	},
	{
		id: 'gpt-5.6-luna',
		name: 'GPT 5.6 Luna',
		protocol: 'responses',
		contextWindow: 1050000,
		maxOutputTokens: 128000,
		inputModalities: ['text', 'image', 'document'],
		inputPrice: 0.2,
		outputPrice: 1.2,
		supportsToolUse: true,
		supportsStreaming: true,
		effortLevels: ['none', 'low', 'medium', 'high', 'xhigh', 'max'],
	},
	{
		id: 'gpt-5.5',
		name: 'GPT 5.5',
		protocol: 'responses',
		contextWindow: 1050000,
		maxOutputTokens: 128000,
		inputModalities: ['text', 'image', 'document'],
		inputPrice: 5.0,
		outputPrice: 30.0,
		supportsToolUse: true,
		supportsStreaming: true,
		effortLevels: ['none', 'low', 'medium', 'high', 'xhigh'],
	},
	{
		id: 'gpt-5.5-pro',
		name: 'GPT 5.5 Pro',
		protocol: 'responses',
		contextWindow: 1050000,
		maxOutputTokens: 128000,
		inputModalities: ['text', 'image', 'document'],
		inputPrice: 30.0,
		outputPrice: 180.0,
		supportsToolUse: true,
		supportsStreaming: true,
		effortLevels: ['medium', 'high', 'xhigh'],
	},
	{
		id: 'gpt-5.4',
		name: 'GPT 5.4',
		protocol: 'responses',
		contextWindow: 1050000,
		maxOutputTokens: 128000,
		inputModalities: ['text', 'image', 'document'],
		inputPrice: 2.5,
		outputPrice: 15.0,
		supportsToolUse: true,
		supportsStreaming: true,
		effortLevels: ['none', 'low', 'medium', 'high', 'xhigh'],
	},
	{
		id: 'gpt-5.4-pro',
		name: 'GPT 5.4 Pro',
		protocol: 'responses',
		contextWindow: 1050000,
		maxOutputTokens: 128000,
		inputModalities: ['text', 'image', 'document'],
		inputPrice: 30.0,
		outputPrice: 180.0,
		supportsToolUse: true,
		supportsStreaming: true,
		effortLevels: ['medium', 'high', 'xhigh'],
	},
	{
		id: 'gpt-5.4-mini',
		name: 'GPT 5.4 Mini',
		protocol: 'responses',
		contextWindow: 400000,
		maxOutputTokens: 128000,
		inputModalities: ['text', 'image', 'document'],
		inputPrice: 0.75,
		outputPrice: 4.5,
		supportsToolUse: true,
		supportsStreaming: true,
		effortLevels: ['none', 'low', 'medium', 'high', 'xhigh'],
	},
	{
		id: 'gpt-5.4-nano',
		name: 'GPT 5.4 Nano',
		protocol: 'responses',
		contextWindow: 400000,
		maxOutputTokens: 128000,
		inputModalities: ['text', 'image', 'document'],
		inputPrice: 0.2,
		outputPrice: 1.25,
		supportsToolUse: true,
		supportsStreaming: true,
		effortLevels: ['none', 'low', 'medium', 'high', 'xhigh'],
	},
	{
		id: 'gpt-5.3-codex',
		name: 'GPT 5.3 Codex',
		protocol: 'responses',
		contextWindow: 400000,
		maxOutputTokens: 128000,
		inputModalities: ['text', 'image', 'document'],
		inputPrice: 1.75,
		outputPrice: 14.0,
		supportsToolUse: true,
		supportsStreaming: true,
		effortLevels: ['none', 'low', 'medium', 'high', 'xhigh'],
	},
	{
		id: 'gpt-5.3-codex-spark',
		name: 'GPT 5.3 Codex Spark',
		protocol: 'responses',
		contextWindow: 128000,
		maxOutputTokens: 128000,
		inputModalities: ['text'],
		inputPrice: 1.75,
		outputPrice: 14.0,
		supportsToolUse: true,
		supportsStreaming: true,
		effortLevels: ['low', 'medium', 'high', 'xhigh'],
	},
	{
		id: 'gpt-5.2',
		name: 'GPT 5.2',
		protocol: 'responses',
		contextWindow: 400000,
		maxOutputTokens: 128000,
		inputModalities: ['text', 'image'],
		inputPrice: 1.75,
		outputPrice: 14.0,
		supportsToolUse: true,
		supportsStreaming: true,
		effortLevels: ['none', 'low', 'medium', 'high', 'xhigh'],
	},
	{
		id: 'gpt-5.1',
		name: 'GPT 5.1',
		protocol: 'responses',
		contextWindow: 400000,
		maxOutputTokens: 128000,
		inputModalities: ['text', 'image'],
		inputPrice: 1.07,
		outputPrice: 8.5,
		supportsToolUse: true,
		supportsStreaming: true,
		effortLevels: ['none', 'low', 'medium', 'high'],
	},
	{
		id: 'gpt-5',
		name: 'GPT 5',
		protocol: 'responses',
		contextWindow: 400000,
		maxOutputTokens: 128000,
		inputModalities: ['text', 'image'],
		inputPrice: 1.07,
		outputPrice: 8.5,
		supportsToolUse: true,
		supportsStreaming: true,
		effortLevels: ['minimal', 'low', 'medium', 'high'],
	},
	{
		id: 'gpt-5-nano',
		name: 'GPT 5 Nano',
		protocol: 'responses',
		contextWindow: 400000,
		maxOutputTokens: 128000,
		inputModalities: ['text', 'image'],
		inputPrice: 0.05,
		outputPrice: 0.4,
		supportsToolUse: true,
		supportsStreaming: true,
		effortLevels: ['minimal', 'low', 'medium', 'high'],
	},
	{
		id: 'claude-fable-5-1',
		name: 'Claude Fable 5.1',
		protocol: 'messages',
		contextWindow: 1000000,
		maxOutputTokens: 128000,
		inputModalities: ['text', 'image', 'document'],
		inputPrice: 10.0,
		outputPrice: 50.0,
		supportsToolUse: true,
		supportsStreaming: true,
		effortLevels: ['low', 'medium', 'high', 'xhigh', 'max'],
	},
	{
		id: 'claude-fable-5',
		name: 'Claude Fable 5',
		protocol: 'messages',
		contextWindow: 1000000,
		maxOutputTokens: 128000,
		inputModalities: ['text', 'image', 'document'],
		inputPrice: 10.0,
		outputPrice: 50.0,
		supportsToolUse: true,
		supportsStreaming: true,
		effortLevels: ['low', 'medium', 'high', 'xhigh', 'max'],
	},
	{
		id: 'claude-opus-5',
		name: 'Claude Opus 5',
		protocol: 'messages',
		contextWindow: 1000000,
		maxOutputTokens: 128000,
		inputModalities: ['text', 'image', 'document'],
		inputPrice: 5.0,
		outputPrice: 25.0,
		supportsToolUse: true,
		supportsStreaming: true,
		effortLevels: ['low', 'medium', 'high', 'xhigh', 'max'],
	},
	{
		id: 'claude-opus-4-8',
		name: 'Claude Opus 4.8',
		protocol: 'messages',
		contextWindow: 1000000,
		maxOutputTokens: 128000,
		inputModalities: ['text', 'image', 'document'],
		inputPrice: 5.0,
		outputPrice: 25.0,
		supportsToolUse: true,
		supportsStreaming: true,
		effortLevels: ['low', 'medium', 'high', 'xhigh', 'max'],
	},
	{
		id: 'claude-opus-4-7',
		name: 'Claude Opus 4.7',
		protocol: 'messages',
		contextWindow: 1000000,
		maxOutputTokens: 128000,
		inputModalities: ['text', 'image', 'document'],
		inputPrice: 5.0,
		outputPrice: 25.0,
		supportsToolUse: true,
		supportsStreaming: true,
		effortLevels: ['low', 'medium', 'high', 'xhigh', 'max'],
	},
	{
		id: 'claude-opus-4-6',
		name: 'Claude Opus 4.6',
		protocol: 'messages',
		contextWindow: 1000000,
		maxOutputTokens: 128000,
		inputModalities: ['text', 'image', 'document'],
		inputPrice: 5.0,
		outputPrice: 25.0,
		supportsToolUse: true,
		supportsStreaming: true,
		effortLevels: ['low', 'medium', 'high', 'max'],
	},
	{
		id: 'claude-opus-4-5',
		name: 'Claude Opus 4.5',
		protocol: 'messages',
		contextWindow: 200000,
		maxOutputTokens: 64000,
		inputModalities: ['text', 'image', 'document'],
		inputPrice: 5.0,
		outputPrice: 25.0,
		supportsToolUse: true,
		supportsStreaming: true,
		effortLevels: ['low', 'medium', 'high'],
	},
	{
		id: 'claude-sonnet-5',
		name: 'Claude Sonnet 5',
		protocol: 'messages',
		contextWindow: 1000000,
		maxOutputTokens: 128000,
		inputModalities: ['text', 'image', 'document'],
		inputPrice: 2.0,
		outputPrice: 10.0,
		supportsToolUse: true,
		supportsStreaming: true,
		effortLevels: ['low', 'medium', 'high', 'xhigh', 'max'],
	},
	{
		id: 'claude-sonnet-4-6',
		name: 'Claude Sonnet 4.6',
		protocol: 'messages',
		contextWindow: 1000000,
		maxOutputTokens: 64000,
		inputModalities: ['text', 'image', 'document'],
		inputPrice: 3.0,
		outputPrice: 15.0,
		supportsToolUse: true,
		supportsStreaming: true,
		effortLevels: ['low', 'medium', 'high', 'max'],
	},
	{
		id: 'claude-sonnet-4-5',
		name: 'Claude Sonnet 4.5',
		protocol: 'messages',
		contextWindow: 1000000,
		maxOutputTokens: 64000,
		inputModalities: ['text', 'image', 'document'],
		inputPrice: 3.0,
		outputPrice: 15.0,
		supportsToolUse: true,
		supportsStreaming: true,
		effortLevels: [],
	},
	{
		id: 'claude-haiku-4-5',
		name: 'Claude Haiku 4.5',
		protocol: 'messages',
		contextWindow: 200000,
		maxOutputTokens: 64000,
		inputModalities: ['text', 'image', 'document'],
		inputPrice: 1.0,
		outputPrice: 5.0,
		supportsToolUse: true,
		supportsStreaming: true,
		effortLevels: [],
	},
	{
		id: 'gemini-3.8-flash',
		name: 'Gemini 3.8 Flash',
		protocol: 'google',
		contextWindow: 1048576,
		maxOutputTokens: 65536,
		inputModalities: ['text', 'image', 'document'],
		inputPrice: 1.5,
		outputPrice: 7.5,
		supportsToolUse: true,
		supportsStreaming: true,
		effortLevels: ['low', 'medium', 'high'],
	},
	{
		id: 'gemini-3.7-flash',
		name: 'Gemini 3.7 Flash',
		protocol: 'google',
		contextWindow: 1048576,
		maxOutputTokens: 65536,
		inputModalities: ['text', 'image', 'document'],
		inputPrice: 1.5,
		outputPrice: 7.5,
		supportsToolUse: true,
		supportsStreaming: true,
		effortLevels: ['low', 'medium', 'high'],
	},
	{
		id: 'gemini-3.6-flash',
		name: 'Gemini 3.6 Flash',
		protocol: 'google',
		contextWindow: 1048576,
		maxOutputTokens: 65536,
		inputModalities: ['text', 'image', 'document'],
		inputPrice: 1.5,
		outputPrice: 7.5,
		supportsToolUse: true,
		supportsStreaming: true,
		effortLevels: ['minimal', 'low', 'medium', 'high'],
	},
	{
		id: 'gemini-3.5-flash',
		name: 'Gemini 3.5 Flash',
		protocol: 'google',
		contextWindow: 1048576,
		maxOutputTokens: 65536,
		inputModalities: ['text', 'image', 'document'],
		inputPrice: 1.5,
		outputPrice: 9.0,
		supportsToolUse: true,
		supportsStreaming: true,
		effortLevels: ['minimal', 'low', 'medium', 'high'],
	},
	{
		id: 'gemini-3.5-flash-lite',
		name: 'Gemini 3.5 Flash Lite',
		protocol: 'google',
		contextWindow: 1048576,
		maxOutputTokens: 65536,
		inputModalities: ['text', 'image', 'document'],
		inputPrice: 0.3,
		outputPrice: 2.5,
		supportsToolUse: true,
		supportsStreaming: true,
		effortLevels: ['minimal', 'low', 'medium', 'high'],
	},
	{
		id: 'gemini-3.1-pro',
		name: 'Gemini 3.1 Pro',
		protocol: 'google',
		contextWindow: 1048576,
		maxOutputTokens: 65536,
		inputModalities: ['text', 'image', 'document'],
		inputPrice: 2.0,
		outputPrice: 12.0,
		supportsToolUse: true,
		supportsStreaming: true,
		effortLevels: ['low', 'medium', 'high'],
	},
	{
		id: 'gemini-3-flash',
		name: 'Gemini 3 Flash',
		protocol: 'google',
		contextWindow: 1048576,
		maxOutputTokens: 65536,
		inputModalities: ['text', 'image', 'document'],
		inputPrice: 0.5,
		outputPrice: 3.0,
		supportsToolUse: true,
		supportsStreaming: true,
		effortLevels: ['minimal', 'low', 'medium', 'high'],
	},
	{
		id: 'grok-4.6',
		name: 'Grok 4.6',
		protocol: 'responses',
		contextWindow: 500000,
		maxOutputTokens: 500000,
		inputModalities: ['text', 'image'],
		inputPrice: 2.0,
		outputPrice: 6.0,
		supportsToolUse: true,
		supportsStreaming: true,
		effortLevels: ['low', 'medium', 'high', 'xhigh'],
	},
	{
		id: 'grok-4.5',
		name: 'Grok 4.5',
		protocol: 'responses',
		contextWindow: 500000,
		maxOutputTokens: 500000,
		inputModalities: ['text', 'image'],
		inputPrice: 2.0,
		outputPrice: 6.0,
		supportsToolUse: true,
		supportsStreaming: true,
		effortLevels: ['low', 'medium', 'high'],
	},
	{
		id: 'grok-build-0.1',
		name: 'Grok Build 0.1',
		protocol: 'responses',
		contextWindow: 256000,
		maxOutputTokens: 256000,
		inputModalities: ['text', 'image', 'document'],
		inputPrice: 1.0,
		outputPrice: 2.0,
		supportsToolUse: true,
		supportsStreaming: true,
		effortLevels: [],
	},
	{
		id: 'muse-spark-1.3',
		name: 'Muse Spark 1.3',
		protocol: 'responses',
		contextWindow: 1048576,
		maxOutputTokens: 131072,
		inputModalities: ['text', 'image', 'document'],
		inputPrice: 1.25,
		outputPrice: 4.25,
		supportsToolUse: true,
		supportsStreaming: true,
		effortLevels: ['minimal', 'low', 'medium', 'high', 'xhigh', 'max'],
	},
	{
		id: 'muse-spark-1.2',
		name: 'Muse Spark 1.2',
		protocol: 'responses',
		contextWindow: 1048576,
		maxOutputTokens: 131072,
		inputModalities: ['text', 'image', 'document'],
		inputPrice: 1.25,
		outputPrice: 4.25,
		supportsToolUse: true,
		supportsStreaming: true,
		effortLevels: ['minimal', 'low', 'medium', 'high', 'xhigh'],
	},
	{
		id: 'qwen3.6-plus',
		name: 'Qwen3.6 Plus',
		protocol: 'messages',
		contextWindow: 262144,
		maxOutputTokens: 65536,
		inputModalities: ['text', 'image'],
		inputPrice: 0.5,
		outputPrice: 3.0,
		supportsToolUse: true,
		supportsStreaming: true,
		effortLevels: [],
	},
	{
		id: 'qwen3.5-plus',
		name: 'Qwen3.5 Plus',
		protocol: 'messages',
		contextWindow: 262144,
		maxOutputTokens: 65536,
		inputModalities: ['text', 'image'],
		inputPrice: 0.2,
		outputPrice: 1.2,
		supportsToolUse: true,
		supportsStreaming: true,
		effortLevels: [],
	},
	{
		id: 'deepseek-v4-pro',
		name: 'DeepSeek V4 Pro',
		protocol: 'chat',
		contextWindow: 1000000,
		maxOutputTokens: 384000,
		inputModalities: ['text'],
		inputPrice: 1.74,
		outputPrice: 3.48,
		supportsToolUse: true,
		supportsStreaming: true,
		effortLevels: ['high', 'max'],
	},
	{
		id: 'deepseek-v4-flash',
		name: 'DeepSeek V4 Flash',
		protocol: 'chat',
		contextWindow: 1000000,
		maxOutputTokens: 384000,
		inputModalities: ['text'],
		inputPrice: 0.14,
		outputPrice: 0.28,
		supportsToolUse: true,
		supportsStreaming: true,
		effortLevels: ['low', 'high', 'max'],
	},
	{
		id: 'deepseek-v4-flash-vision-exp',
		name: 'DeepSeek V4 Flash Vision Exp',
		protocol: 'chat',
		contextWindow: 1000000,
		maxOutputTokens: 384000,
		inputModalities: ['text', 'image'],
		inputPrice: 0.14,
		outputPrice: 0.28,
		supportsToolUse: true,
		supportsStreaming: true,
		effortLevels: ['low', 'high', 'max'],
	},
	{
		id: 'minimax-m3',
		name: 'MiniMax M3',
		protocol: 'chat',
		contextWindow: 512000,
		maxOutputTokens: 128000,
		inputModalities: ['text', 'image'],
		inputPrice: 0.3,
		outputPrice: 1.2,
		supportsToolUse: true,
		supportsStreaming: true,
		effortLevels: [],
	},
	{
		id: 'minimax-m2.7',
		name: 'MiniMax M2.7',
		protocol: 'chat',
		contextWindow: 204800,
		maxOutputTokens: 131072,
		inputModalities: ['text'],
		inputPrice: 0.3,
		outputPrice: 1.2,
		supportsToolUse: true,
		supportsStreaming: true,
		effortLevels: [],
	},
	{
		id: 'glm-5.3-flash',
		name: 'GLM 5.3 Flash',
		protocol: 'chat',
		contextWindow: 1000000,
		maxOutputTokens: 131072,
		inputModalities: ['text', 'image', 'document'],
		inputPrice: 0.15,
		outputPrice: 0.5,
		supportsToolUse: true,
		supportsStreaming: true,
		effortLevels: ['low', 'high', 'max'],
	},
	{
		id: 'glm-5.3',
		name: 'GLM 5.3',
		protocol: 'chat',
		contextWindow: 1000000,
		maxOutputTokens: 131072,
		inputModalities: ['text'],
		inputPrice: 1.4,
		outputPrice: 4.4,
		supportsToolUse: true,
		supportsStreaming: true,
		effortLevels: ['low', 'high', 'max'],
	},
	{
		id: 'glm-5.2',
		name: 'GLM 5.2',
		protocol: 'chat',
		contextWindow: 1000000,
		maxOutputTokens: 131072,
		inputModalities: ['text'],
		inputPrice: 1.4,
		outputPrice: 4.4,
		supportsToolUse: true,
		supportsStreaming: true,
		effortLevels: ['high', 'max'],
	},
	{
		id: 'glm-5.1',
		name: 'GLM 5.1',
		protocol: 'chat',
		contextWindow: 204800,
		maxOutputTokens: 131072,
		inputModalities: ['text'],
		inputPrice: 1.4,
		outputPrice: 4.4,
		supportsToolUse: true,
		supportsStreaming: true,
		effortLevels: [],
	},
	{
		id: 'kimi-k2.6',
		name: 'Kimi K2.6',
		protocol: 'chat',
		contextWindow: 262144,
		maxOutputTokens: 65536,
		inputModalities: ['text', 'image'],
		inputPrice: 0.95,
		outputPrice: 4.0,
		supportsToolUse: true,
		supportsStreaming: true,
		effortLevels: [],
	},
	{
		id: 'kimi-k2.7-code',
		name: 'Kimi K2.7 Code',
		protocol: 'chat',
		contextWindow: 262144,
		maxOutputTokens: 262144,
		inputModalities: ['text', 'image'],
		inputPrice: 0.95,
		outputPrice: 4.0,
		supportsToolUse: true,
		supportsStreaming: true,
		effortLevels: [],
	},
	{
		id: 'kimi-k3',
		name: 'Kimi K3',
		protocol: 'chat',
		contextWindow: 1048576,
		maxOutputTokens: 131072,
		inputModalities: ['text', 'image'],
		inputPrice: 3.0,
		outputPrice: 15.0,
		supportsToolUse: true,
		supportsStreaming: true,
		effortLevels: ['max'],
	},
	{
		id: 'big-pickle',
		name: 'Big Pickle',
		protocol: 'chat',
		contextWindow: 200000,
		maxOutputTokens: 32000,
		inputModalities: ['text'],
		inputPrice: 0,
		outputPrice: 0,
		supportsToolUse: true,
		supportsStreaming: true,
		effortLevels: [],
	},
	{
		id: 'mimo-v2.5-free',
		name: 'MiMo-V2.5 Free',
		protocol: 'chat',
		contextWindow: 200000,
		maxOutputTokens: 32000,
		inputModalities: ['text', 'image'],
		inputPrice: 0,
		outputPrice: 0,
		supportsToolUse: true,
		supportsStreaming: true,
		effortLevels: [],
	},
	{
		id: 'ling-3.0-flash-fin-free',
		name: 'Ling 3.0 Flash Fin Free',
		protocol: 'chat',
		contextWindow: 262144,
		maxOutputTokens: 32768,
		inputModalities: ['text'],
		inputPrice: 0,
		outputPrice: 0,
		supportsToolUse: true,
		supportsStreaming: true,
		effortLevels: [],
	},
	{
		id: 'nemotron-3-ultra-free',
		name: 'Nemotron 3 Ultra Free',
		protocol: 'chat',
		contextWindow: 1000000,
		maxOutputTokens: 128000,
		inputModalities: ['text'],
		inputPrice: 0,
		outputPrice: 0,
		supportsToolUse: true,
		supportsStreaming: true,
		effortLevels: [],
	},
	{
		id: 'nemotron-3.5-lightning-free',
		name: 'Nemotron 3.5 Lightning Free',
		protocol: 'chat',
		contextWindow: 262144,
		maxOutputTokens: 262144,
		inputModalities: ['text'],
		inputPrice: 0,
		outputPrice: 0,
		supportsToolUse: true,
		supportsStreaming: true,
		effortLevels: [],
	},
	{
		id: 'muse-spark-1.3-contributor-free',
		name: 'Muse Spark 1.3 Contributor Free',
		protocol: 'responses',
		contextWindow: 1048576,
		maxOutputTokens: 131072,
		inputModalities: ['text', 'image', 'document'],
		inputPrice: 0,
		outputPrice: 0,
		supportsToolUse: true,
		supportsStreaming: true,
		effortLevels: ['minimal', 'low', 'medium', 'high', 'xhigh'],
	},
])

const GO_MODELS = freezeModels([
	{
		id: 'grok-4.6',
		name: 'Grok 4.6',
		protocol: 'responses',
		contextWindow: 500000,
		maxOutputTokens: 500000,
		inputModalities: ['text', 'image'],
		inputPrice: 2.0,
		outputPrice: 6.0,
		supportsToolUse: true,
		supportsStreaming: true,
		effortLevels: ['low', 'medium', 'high', 'xhigh'],
	},
	{
		id: 'gpt-5.6-luna',
		name: 'GPT 5.6 Luna',
		protocol: 'responses',
		contextWindow: 1050000,
		maxOutputTokens: 128000,
		inputModalities: ['text', 'image', 'document'],
		inputPrice: 0.2,
		outputPrice: 1.2,
		supportsToolUse: true,
		supportsStreaming: true,
		effortLevels: ['none', 'low', 'medium', 'high', 'xhigh', 'max'],
	},
	{
		id: 'glm-5.3-flash',
		name: 'GLM-5.3-Flash',
		protocol: 'chat',
		contextWindow: 1000000,
		maxOutputTokens: 131072,
		inputModalities: ['text', 'image', 'document'],
		inputPrice: 0.15,
		outputPrice: 0.5,
		supportsToolUse: true,
		supportsStreaming: true,
		effortLevels: ['low', 'high', 'max'],
	},
	{
		id: 'glm-5.3',
		name: 'GLM-5.3',
		protocol: 'chat',
		contextWindow: 1000000,
		maxOutputTokens: 131072,
		inputModalities: ['text'],
		inputPrice: 1.4,
		outputPrice: 4.4,
		supportsToolUse: true,
		supportsStreaming: true,
		effortLevels: ['low', 'high', 'max'],
	},
	{
		id: 'glm-5.2',
		name: 'GLM-5.2',
		protocol: 'chat',
		contextWindow: 1000000,
		maxOutputTokens: 131072,
		inputModalities: ['text'],
		inputPrice: 1.4,
		outputPrice: 4.4,
		supportsToolUse: true,
		supportsStreaming: true,
		effortLevels: ['high', 'max'],
	},
	{
		id: 'glm-5.1',
		name: 'GLM-5.1',
		protocol: 'chat',
		contextWindow: 202752,
		maxOutputTokens: 32768,
		inputModalities: ['text'],
		inputPrice: 1.4,
		outputPrice: 4.4,
		supportsToolUse: true,
		supportsStreaming: true,
		effortLevels: [],
	},
	{
		id: 'kimi-k3',
		name: 'Kimi K3',
		protocol: 'chat',
		contextWindow: 1048576,
		maxOutputTokens: 131072,
		inputModalities: ['text', 'image'],
		inputPrice: 3.0,
		outputPrice: 15.0,
		supportsToolUse: true,
		supportsStreaming: true,
		effortLevels: ['max'],
	},
	{
		id: 'kimi-k2.7-code',
		name: 'Kimi K2.7 Code',
		protocol: 'chat',
		contextWindow: 262144,
		maxOutputTokens: 262144,
		inputModalities: ['text', 'image'],
		inputPrice: 0.95,
		outputPrice: 4.0,
		supportsToolUse: true,
		supportsStreaming: true,
		effortLevels: [],
	},
	{
		id: 'kimi-k2.6',
		name: 'Kimi K2.6',
		protocol: 'chat',
		contextWindow: 262144,
		maxOutputTokens: 65536,
		inputModalities: ['text', 'image'],
		inputPrice: 0.95,
		outputPrice: 4.0,
		supportsToolUse: true,
		supportsStreaming: true,
		effortLevels: [],
	},
	{
		id: 'longcat-2.0',
		name: 'LongCat-2.0',
		protocol: 'chat',
		contextWindow: 1000000,
		maxOutputTokens: 131072,
		inputModalities: ['text'],
		inputPrice: 0.3,
		outputPrice: 1.2,
		supportsToolUse: true,
		supportsStreaming: true,
		effortLevels: [],
	},
	{
		id: 'deepseek-v4-pro',
		name: 'DeepSeek V4 Pro',
		protocol: 'chat',
		contextWindow: 1000000,
		maxOutputTokens: 384000,
		inputModalities: ['text'],
		inputPrice: 0.66,
		outputPrice: 1.98,
		supportsToolUse: true,
		supportsStreaming: true,
		effortLevels: ['high', 'max'],
	},
	{
		id: 'deepseek-v4-flash',
		name: 'DeepSeek V4 Flash',
		protocol: 'chat',
		contextWindow: 1000000,
		maxOutputTokens: 384000,
		inputModalities: ['text'],
		inputPrice: 0.22,
		outputPrice: 0.66,
		supportsToolUse: true,
		supportsStreaming: true,
		effortLevels: ['low', 'high', 'max'],
	},
	{
		id: 'deepseek-v4-flash-vision-exp',
		name: 'DeepSeek V4 Flash Vision Exp',
		protocol: 'chat',
		contextWindow: 1000000,
		maxOutputTokens: 384000,
		inputModalities: ['text', 'image'],
		inputPrice: 0.22,
		outputPrice: 0.66,
		supportsToolUse: true,
		supportsStreaming: true,
		effortLevels: ['low', 'high', 'max'],
	},
	{
		id: 'mimo-v2.5',
		name: 'MiMo-V2.5',
		protocol: 'chat',
		contextWindow: 1000000,
		maxOutputTokens: 128000,
		inputModalities: ['text', 'image'],
		inputPrice: 0.14,
		outputPrice: 0.28,
		supportsToolUse: true,
		supportsStreaming: true,
		effortLevels: [],
	},
	{
		id: 'mimo-v2.5-pro',
		name: 'MiMo-V2.5-Pro',
		protocol: 'chat',
		contextWindow: 1048576,
		maxOutputTokens: 128000,
		inputModalities: ['text'],
		inputPrice: 0.435,
		outputPrice: 0.87,
		supportsToolUse: true,
		supportsStreaming: true,
		effortLevels: [],
	},
	{
		id: 'minimax-m3',
		name: 'MiniMax M3',
		protocol: 'messages',
		contextWindow: 1000000,
		maxOutputTokens: 131072,
		inputModalities: ['text', 'image'],
		inputPrice: 0.3,
		outputPrice: 1.2,
		supportsToolUse: true,
		supportsStreaming: true,
		effortLevels: [],
	},
	{
		id: 'minimax-m2.7',
		name: 'MiniMax M2.7',
		protocol: 'messages',
		contextWindow: 204800,
		maxOutputTokens: 131072,
		inputModalities: ['text'],
		inputPrice: 0.3,
		outputPrice: 1.2,
		supportsToolUse: true,
		supportsStreaming: true,
		effortLevels: [],
	},
	{
		id: 'muse-spark-1.3-contributor',
		name: 'Muse Spark 1.3 Contributor',
		protocol: 'responses',
		contextWindow: 1048576,
		maxOutputTokens: 131072,
		inputModalities: ['text', 'image', 'document'],
		inputPrice: 0.1,
		outputPrice: 0.2,
		supportsToolUse: true,
		supportsStreaming: true,
		effortLevels: ['minimal', 'low', 'medium', 'high', 'xhigh'],
	},
	{
		id: 'muse-spark-1.2-contributor',
		name: 'Muse Spark 1.2 Contributor',
		protocol: 'responses',
		contextWindow: 1048576,
		maxOutputTokens: 131072,
		inputModalities: ['text', 'image', 'document'],
		inputPrice: 0.1,
		outputPrice: 0.2,
		supportsToolUse: true,
		supportsStreaming: true,
		effortLevels: ['minimal', 'low', 'medium', 'high', 'xhigh'],
	},
	{
		id: 'qwen3.8-max',
		name: 'Qwen3.8 Max',
		protocol: 'messages',
		contextWindow: 1000000,
		maxOutputTokens: 131072,
		inputModalities: ['text', 'image'],
		inputPrice: 2.0,
		outputPrice: 6.0,
		supportsToolUse: true,
		supportsStreaming: true,
		effortLevels: ['low', 'medium', 'xhigh'],
	},
	{
		id: 'qwen3.8-flash',
		name: 'Qwen3.8 Flash',
		protocol: 'messages',
		contextWindow: 1000000,
		maxOutputTokens: 131072,
		inputModalities: ['text', 'image'],
		inputPrice: 0.15,
		outputPrice: 0.47,
		supportsToolUse: true,
		supportsStreaming: true,
		effortLevels: ['low', 'medium', 'xhigh'],
	},
	{
		id: 'qwen3.7-max',
		name: 'Qwen3.7 Max',
		protocol: 'messages',
		contextWindow: 1000000,
		maxOutputTokens: 65536,
		inputModalities: ['text'],
		inputPrice: 2.5,
		outputPrice: 7.5,
		supportsToolUse: true,
		supportsStreaming: true,
		effortLevels: [],
	},
	{
		id: 'qwen3.7-plus',
		name: 'Qwen3.7 Plus',
		protocol: 'messages',
		contextWindow: 1000000,
		maxOutputTokens: 65536,
		inputModalities: ['text', 'image'],
		inputPrice: 0.4,
		outputPrice: 1.6,
		supportsToolUse: true,
		supportsStreaming: true,
		effortLevels: [],
	},
	{
		id: 'qwen3.6-plus',
		name: 'Qwen3.6 Plus',
		protocol: 'messages',
		contextWindow: 1000000,
		maxOutputTokens: 65536,
		inputModalities: ['text', 'image'],
		inputPrice: 0.5,
		outputPrice: 3.0,
		supportsToolUse: true,
		supportsStreaming: true,
		effortLevels: [],
	},
	{
		id: 'hy4-preview',
		name: 'Hy4 preview',
		protocol: 'chat',
		contextWindow: 1024000,
		maxOutputTokens: 64000,
		inputModalities: ['text'],
		inputPrice: 0.834,
		outputPrice: 2.501,
		supportsToolUse: true,
		supportsStreaming: true,
		effortLevels: ['none', 'high'],
	},
	{
		id: 'hy3',
		name: 'Hy3',
		protocol: 'chat',
		contextWindow: 256000,
		maxOutputTokens: 128000,
		inputModalities: ['text'],
		inputPrice: 0.14,
		outputPrice: 0.58,
		supportsToolUse: true,
		supportsStreaming: true,
		effortLevels: ['none', 'low', 'high'],
	},
	{
		id: 'omen-alpha',
		name: 'Omen Alpha',
		protocol: 'chat',
		contextWindow: 500000,
		maxOutputTokens: 128000,
		inputModalities: ['text', 'image'],
		inputPrice: 0.2,
		outputPrice: 0.66,
		supportsToolUse: true,
		supportsStreaming: true,
		effortLevels: ['low', 'high'],
	},
])

/** Supported metadata; actual account availability is established by live discovery. */
export function getZenModels(service: ZenService): readonly ZenModel[] {
	return service === 'zen' ? ZEN_MODELS : GO_MODELS
}

/** Exact wire ID lookup. Zen CLI prefixes and unknown IDs are not guessed. */
export function findZenModel(service: ZenService, id: string): ZenModel | undefined {
	return getZenModels(service).find((model) => model.id === id)
}
